# Generated by Django 4.2 on 2024-04-11 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_product_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('transaction_time', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('transaction_qty', models.IntegerField(null=True)),
                ('store_id', models.IntegerField(null=True)),
                ('store_location', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('unit_price', models.FloatField(null=True)),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_timestamp',
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
